### ISSUE TITLE
Custom color for each tab

### ISSUE THREAD

**Issue by CherubicBoot** [MarkChan0225/RoundedDiscord#13]
Hii! I'm wondering if it's possible to change the color of specific tabs, as in this screenshot? For example, I want my channel list to be green, the chat menu to be red, and the member list to be blue. Currently, I'm using Vencord's client theme plugin, which can change the entire color scheme but not individual tabs. Thanks in advance! 

![image](https://github.com/user-attachments/assets/09cf9d45-530f-44a0-bec7-9d754b711ed1)

**Comment by MarkChan0225** [comment]
Yes, it is. However, I am busy at the moment, you can go to ur client mod server's custom-css chanel to ask for help
